### ISSUE TITLE
你好，我想问一下，您的（依存分析：基于序列标注的中文依存句法分析模型实现   https://blog.csdn.net/sinat_33741547/article/details/79321401），对语料的预处理的程序能提供一下吗？还有我的呈现报错，错误为：ConfigParser.NoSectionError: No section: 'depparser'

### ISSUE THREAD

**Issue by mawenju203** [lpty/nlp_base#10]
你好，我想问一下，您的（依存分析：基于序列标注的中文依存句法分析模型实现   https://blog.csdn.net/sinat_33741547/article/details/79321401），对语料的预处理的程序能提供一下吗？还有我的呈现报错，错误为：ConfigParser.NoSectionError: No section: 'depparser'，如果可以能远程指导一下吗？都调试了好多天了，联系：1601258093@qq.com.
您的分词的代码，我已经调通，非常希望能得到您的帮助

**Comment by lpty** [comment]
配置文件问题
