### ISSUE TITLE
关于NER的F1值

### ISSUE THREAD

**Issue by chuanfanyoudong** [lpty/nlp_base#11]
你好；

有幸看到你的代码，我在跑CRF的时候，想问一下，用类别（BIO）做的F1是不是不好啊，我感觉应该用实际的识别出的实体的结果做F1会好一点？

**Comment by lpty** [comment]
@chuanfanyoudong 你好，是的，具体评价指标还是要根据业务来定，这里只是简单的demo。

**Comment by chuanfanyoudong** [comment]
@lpty 你好；谢谢您的回复。
