### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by slobLX** [lpty/nlp_base#12]
When I use 'from interrogative.api import *'

The error occurs:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/lx/nlp_base/interrogative/interrogative/api.py", line 7, in <module>
    from model import get_model
ModuleNotFoundError: No module named 'model'

**Comment by lpty** [comment]
@SLOCAT remove 'interrogative' floder out of 'nlp_base', and replace 'from model import get_model' with "from interrogative.model import get_model"

**Comment by slobLX** [comment]
What is the version of python you are using?

**Comment by lpty** [comment]
push a new version of py3
