### ISSUE TITLE
中文疑问句判别模型出来的结果都是统一分值

### ISSUE THREAD

**Issue by luweishuang** [lpty/nlp_base#8]
我自己制作了数据集来训练中文疑问句判别模型，测试的时候，无论输入什么样的句子，都是一样的得分prob, 并且都是负类，求原因？

**Comment by luweishuang** [comment]
找到错误了，测试句子必须是分词后的句子，可以在测试过程中增加 jieba 分词模块，另 项目会建立自己的词典，若测试用例分词后的词不在词典中，可能有问题

**Comment by TangYang1** [comment]
> 我自己制作了数据集来训练中文疑问句判别模型，测试的时候，无论输入什么样的句子，都是一样的得分prob, 并且都是负类，求原因？

请问训练数据你是在哪里找到的，GitHub上没有欸
